[package]
name = "bfs-rust"
version = "0.1.0"
authors = ["Geoffrey Thomas <geofft@ldpreload.com>", "Luis Gerhorst <bfs-rust@luisgerhorst.de>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
linux-kernel-module = { path = "linux-kernel-module-rust" }
